package com.publiccar.code.model;
// default package
// Generated 2018-5-23 17:35:35 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Annual generated by hbm2java
 */
@Entity
@Table(name = "annual", catalog = "publiccar")
public class Annual implements java.io.Serializable {

	private Integer annualId;
	private Integer carId;
	private Integer driverId;
	private String annualContent;
	private String annualBegindate;
	private String annualEndate;

	public Annual() {
	}

	public Annual(Integer carId, Integer driverId, String annualContent, String annualBegindate, String annualEndate) {
		this.carId = carId;
		this.driverId = driverId;
		this.annualContent = annualContent;
		this.annualBegindate = annualBegindate;
		this.annualEndate = annualEndate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "annual_id", unique = true, nullable = false)
	public Integer getAnnualId() {
		return this.annualId;
	}

	public void setAnnualId(Integer annualId) {
		this.annualId = annualId;
	}

	@Column(name = "car_id")
	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	@Column(name = "driver_id")
	public Integer getDriverId() {
		return this.driverId;
	}

	public void setDriverId(Integer driverId) {
		this.driverId = driverId;
	}

	@Column(name = "annual_content", length = 100)
	public String getAnnualContent() {
		return this.annualContent;
	}

	public void setAnnualContent(String annualContent) {
		this.annualContent = annualContent;
	}

	@Column(name = "annual_begindate")
	public String getAnnualBegindate() {
		return this.annualBegindate;
	}

	public void setAnnualBegindate(String annualBegindate) {
		this.annualBegindate = annualBegindate;
	}

	@Column(name = "annual_endate")
	public String getAnnualEndate() {
		return this.annualEndate;
	}

	public void setAnnualEndate(String annualEndate) {
		this.annualEndate = annualEndate;
	}

}
