package com.publiccar.code.model;
// default package
// Generated 2018-5-23 17:35:35 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Demp generated by hbm2java
 */
@Entity
@Table(name = "demp", catalog = "publiccar")
public class Demp implements java.io.Serializable {

	private Integer dempId;
	private String dempName;

	public Demp() {
	}

	public Demp(String dempName) {
		this.dempName = dempName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "demp_id", unique = true, nullable = false)
	public Integer getDempId() {
		return this.dempId;
	}

	public void setDempId(Integer dempId) {
		this.dempId = dempId;
	}

	@Column(name = "demp_name")
	public String getDempName() {
		return this.dempName;
	}

	public void setDempName(String dempName) {
		this.dempName = dempName;
	}

}
