package com.publiccar.code.model;
// default package
// Generated 2018-5-31 14:11:43 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dispatch generated by hbm2java
 */
@Entity
@Table(name = "dispatch", catalog = "publiccar")
public class Dispatch implements java.io.Serializable {

	private Integer dispatchId;
	private Integer carId;
	private Integer driverId;
	private String driverName;
	private String applicantName;
	private String applicantSex;
	private Integer applicantAge;
	private Integer dempId;
	private Integer dispatchTimeLength;
	private Integer dispatchNumber;
	private String dispatchReason;
	private String dispatchStatus;

	public Dispatch() {
	}

	public Dispatch(Integer carId, Integer driverId, String driverName, String applicantName, String applicantSex,
			Integer applicantAge, Integer dempId, Integer dispatchTimeLength, Integer dispatchNumber,
			String dispatchReason, String dispatchStatus) {
		this.carId = carId;
		this.driverId = driverId;
		this.driverName = driverName;
		this.applicantName = applicantName;
		this.applicantSex = applicantSex;
		this.applicantAge = applicantAge;
		this.dempId = dempId;
		this.dispatchTimeLength = dispatchTimeLength;
		this.dispatchNumber = dispatchNumber;
		this.dispatchReason = dispatchReason;
		this.dispatchStatus = dispatchStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "dispatch_id", unique = true, nullable = false)
	public Integer getDispatchId() {
		return this.dispatchId;
	}

	public void setDispatchId(Integer dispatchId) {
		this.dispatchId = dispatchId;
	}

	@Column(name = "car_id")
	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	@Column(name = "driver_id")
	public Integer getDriverId() {
		return this.driverId;
	}

	public void setDriverId(Integer driverId) {
		this.driverId = driverId;
	}

	@Column(name = "driver_name")
	public String getDriverName() {
		return this.driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	@Column(name = "applicant_name")
	public String getApplicantName() {
		return this.applicantName;
	}

	public void setApplicantName(String applicantName) {
		this.applicantName = applicantName;
	}

	@Column(name = "applicant_sex")
	public String getApplicantSex() {
		return this.applicantSex;
	}

	public void setApplicantSex(String applicantSex) {
		this.applicantSex = applicantSex;
	}

	@Column(name = "applicant_age")
	public Integer getApplicantAge() {
		return this.applicantAge;
	}

	public void setApplicantAge(Integer applicantAge) {
		this.applicantAge = applicantAge;
	}

	@Column(name = "demp_id")
	public Integer getDempId() {
		return this.dempId;
	}

	public void setDempId(Integer dempId) {
		this.dempId = dempId;
	}

	@Column(name = "dispatch_time_length")
	public Integer getDispatchTimeLength() {
		return this.dispatchTimeLength;
	}

	public void setDispatchTimeLength(Integer dispatchTimeLength) {
		this.dispatchTimeLength = dispatchTimeLength;
	}

	@Column(name = "dispatch_number")
	public Integer getDispatchNumber() {
		return this.dispatchNumber;
	}

	public void setDispatchNumber(Integer dispatchNumber) {
		this.dispatchNumber = dispatchNumber;
	}

	@Column(name = "dispatch_reason")
	public String getDispatchReason() {
		return this.dispatchReason;
	}

	public void setDispatchReason(String dispatchReason) {
		this.dispatchReason = dispatchReason;
	}

	@Column(name = "dispatch_status")
	public String getDispatchStatus() {
		return this.dispatchStatus;
	}

	public void setDispatchStatus(String dispatchStatus) {
		this.dispatchStatus = dispatchStatus;
	}

}
