package com.publiccar.code.model;
// default package
// Generated 2018-5-28 15:25:30 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PublicCar generated by hbm2java
 */
@Entity
@Table(name = "public_car", catalog = "publiccar")
public class PublicCar implements java.io.Serializable {

	private Integer carId;
	private String carNumber;
	private String carType;
	private Integer driverId;
	private String driverName;
	private String driverSex;
	private Integer driverAge;
	private String carAnnualStatus;
	private String carAnnualEndtime;
	private String carInsuranceStatus;
	private String carInsuranceEndtime;
	private String carStatus;
	private String dempName;

	public PublicCar() {
	}

	public PublicCar(String carNumber, String carType, Integer driverId, String driverName, String driverSex,
			Integer driverAge, String carAnnualStatus, String carAnnualEndtime, String carInsuranceStatus,
			String carInsuranceEndtime, String carStatus, String dempName) {
		this.carNumber = carNumber;
		this.carType = carType;
		this.driverId = driverId;
		this.driverName = driverName;
		this.driverSex = driverSex;
		this.driverAge = driverAge;
		this.carAnnualStatus = carAnnualStatus;
		this.carAnnualEndtime = carAnnualEndtime;
		this.carInsuranceStatus = carInsuranceStatus;
		this.carInsuranceEndtime = carInsuranceEndtime;
		this.carStatus = carStatus;
		this.dempName = dempName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "car_id", unique = true, nullable = false)
	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	@Column(name = "car_number", length = 50)
	public String getCarNumber() {
		return this.carNumber;
	}

	public void setCarNumber(String carNumber) {
		this.carNumber = carNumber;
	}

	@Column(name = "car_type", length = 100)
	public String getCarType() {
		return this.carType;
	}

	public void setCarType(String carType) {
		this.carType = carType;
	}

	@Column(name = "driver_id")
	public Integer getDriverId() {
		return this.driverId;
	}

	public void setDriverId(Integer driverId) {
		this.driverId = driverId;
	}

	@Column(name = "driver_name")
	public String getDriverName() {
		return this.driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	@Column(name = "driver_sex")
	public String getDriverSex() {
		return this.driverSex;
	}

	public void setDriverSex(String driverSex) {
		this.driverSex = driverSex;
	}

	@Column(name = "driver_age")
	public Integer getDriverAge() {
		return this.driverAge;
	}

	public void setDriverAge(Integer driverAge) {
		this.driverAge = driverAge;
	}

	@Column(name = "car_annual_status")
	public String getCarAnnualStatus() {
		return this.carAnnualStatus;
	}

	public void setCarAnnualStatus(String carAnnualStatus) {
		this.carAnnualStatus = carAnnualStatus;
	}

	@Column(name = "car_annual_endtime")
	public String getCarAnnualEndtime() {
		return this.carAnnualEndtime;
	}

	public void setCarAnnualEndtime(String carAnnualEndtime) {
		this.carAnnualEndtime = carAnnualEndtime;
	}

	@Column(name = "car_insurance_status")
	public String getCarInsuranceStatus() {
		return this.carInsuranceStatus;
	}

	public void setCarInsuranceStatus(String carInsuranceStatus) {
		this.carInsuranceStatus = carInsuranceStatus;
	}

	@Column(name = "car_insurance_endtime")
	public String getCarInsuranceEndtime() {
		return this.carInsuranceEndtime;
	}

	public void setCarInsuranceEndtime(String carInsuranceEndtime) {
		this.carInsuranceEndtime = carInsuranceEndtime;
	}

	@Column(name = "car_status")
	public String getCarStatus() {
		return this.carStatus;
	}

	public void setCarStatus(String carStatus) {
		this.carStatus = carStatus;
	}

	@Column(name = "demp_name")
	public String getDempName() {
		return this.dempName;
	}

	public void setDempName(String dempName) {
		this.dempName = dempName;
	}

}
