package com.publiccar.code.model;
// default package
// Generated 2018-5-23 17:35:35 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "publiccar")
public class User implements java.io.Serializable {

	private Integer userId;
	private Integer dempId;
	private String userUsername;
	private String userPassword;
	private String userIdentity;
	private String userName;
	private String userSex;
	private Integer userAge;
	private String userDemp;
	private String userMoney;

	public User() {
	}

	public User(Integer dempId, String userUsername, String userPassword, String userIdentity, String userName,
			String userSex, Integer userAge, String userDemp, String userMoney) {
		this.dempId = dempId;
		this.userUsername = userUsername;
		this.userPassword = userPassword;
		this.userIdentity = userIdentity;
		this.userName = userName;
		this.userSex = userSex;
		this.userAge = userAge;
		this.userDemp = userDemp;
		this.userMoney = userMoney;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "demp_id")
	public Integer getDempId() {
		return this.dempId;
	}

	public void setDempId(Integer dempId) {
		this.dempId = dempId;
	}

	@Column(name = "user_username", length = 100)
	public String getUserUsername() {
		return this.userUsername;
	}

	public void setUserUsername(String userUsername) {
		this.userUsername = userUsername;
	}

	@Column(name = "user_password", length = 100)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "user_identity", length = 11)
	public String getUserIdentity() {
		return this.userIdentity;
	}

	public void setUserIdentity(String userIdentity) {
		this.userIdentity = userIdentity;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_sex")
	public String getUserSex() {
		return this.userSex;
	}

	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	@Column(name = "user_age")
	public Integer getUserAge() {
		return this.userAge;
	}

	public void setUserAge(Integer userAge) {
		this.userAge = userAge;
	}

	@Column(name = "user_demp")
	public String getUserDemp() {
		return this.userDemp;
	}

	public void setUserDemp(String userDemp) {
		this.userDemp = userDemp;
	}

	@Column(name = "user_money")
	public String getUserMoney() {
		return this.userMoney;
	}

	public void setUserMoney(String userMoney) {
		this.userMoney = userMoney;
	}

}
